# 1.0 Frequency Distributions

## 1.1 Simplifying Data

Previously, we focused on the details around collecting data, on understanding its structure and how it's measured. **Collecting data is just the starting point in a data analysis workflow.** We rarely collect data just for the sake of collecting it. We collect data to analyze it, and we analyze it for different purposes:

- To describe phenomena in the world (science).
- To make better decisions (industries).
- To improve systems (engineering).
- To describe different aspects of our society (data journalism); etc.

<center><img width="250" src="https://drive.google.com/uc?export=view&id=1_QX1g2KHfZVpg5mVsRUO4CJgp0F5StwP"></center>


Our capacity to understand a data set just by looking at it in a table format is limited, and it decreases dramatically as the size of the data set increases. To be able to analyze data, we need to find ways to simplify it.

The WNBA data set we've been working with has 143 rows and 32 columns. This might not seem like much compared to other data sets, but it's still extremely difficult to find any patterns just by eyeballing the data set in a table format. With 32 columns, even five rows would take us a couple of minutes to analyze:

| _ | Name            | Team | Pos | Height | Weight | BMI       | Birth_Place | Birthdate         | Age | College        | Experience | Games Played | MIN |
|---|-----------------|------|-----|--------|--------|-----------|-------------|-------------------|-----|----------------|------------|--------------|-----|
| 0 | Aerial Powers   | DAL  | F   | 183    | 71.0   | 21.200991 | US          | January 17, 1994  | 23  | Michigan State | 2          | 8            | 173 |
| 1 | Alana Beard     | LA   | G/F | 185    | 73.0   | 21.329438 | US          | May 14, 1982      | 35  | Duke           | 12         | 30           | 947 |
| 2 | Alex Bentley    | CON  | G   | 170    | 69.0   | 23.875433 | US          | October 27, 1990  | 26  | Penn State     | 4          | 26           | 617 |
| 3 | Alex Montgomery | SAN  | G/F | 185    | 84.0   | 24.543462 | US          | December 11, 1988 | 28  | Georgia Tech   | 6          | 31           | 721 |
| 4 | Alexis Jones    | MIN  | G   | 175    | 78.0   | 25.469388 | US          | August 5, 1994    | 23  | Baylor         | R          | 24           | 137 |


One way to simplify this data set is to select a variable, count how many times each unique value occurs, and represent the frequencies (the number of times a unique value occurs) in a table. This is how such a table looks for the **POS (player position)** variable:

<left><img width="150" src="https://drive.google.com/uc?export=view&id=1la98ySTe-ElKFokRsXZTsUyb_RsuB8mL"></left>


Because 60 of the players in our data set play as **guards**, the frequency for guards is 60. Because 33 of the players are forwards, the frequency for forwards is 33, and so on.

With the table above, we simplified the **POS variable** by transforming it to a comprehensible format. Instead of having to deal with analyzing 143 values (the length of the POS variable), now we only have five values to analyze. We can make a few conclusions now that would have been difficult and time consuming to reach at just by looking at the list of 143 values:

- We can see how the frequencies are distributed:
  - Almost half of the players play as guards.
  - Most of the players are either guards, forwards or centers.
  - Very few players have combined positions (like guard/forward or forward/center).
- We can make comparisons with ease:
  - There are roughly two times more guards than forwards.
  - There are slightly less centers that forwards; etc.
  
Because the table above shows how frequencies are distributed, it's often called a **frequency distribution table**, or, shorter, **frequency table** or **frequency distribution**. Throughout this mission, our focus will be on learning the details behind this form of simplifying data.


**Exercise**

<img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ">


Try to get a sense for how difficult it is to analyze the **basketball data set** in its original form.

- Read in the basketball data set (the name of the CSV file is **wnba.csv**) using **pd.read_csv()**.
- Using **DataFrame.shape**, find the number of rows and columns of the data set.
- Print the entire data set, and try to analyze the output to find some patterns.

In [1]:
import pandas as pd

pd.options.display.max_rows = 200
pd.options.display.max_columns = 50

# put your code here
wnba = pd.read_csv("wnba.csv")
print("Linhas: {}  Colunas: {}".format(wnba.shape[0], wnba.shape[1]))
wnba

Linhas: 143  Colunas: 32

,Name,Team,Pos,Height,Weight,BMI,Birth_Place,Birthdate,Age,College,Experience,Games Played,MIN,FGM,FGA,FG%,15:00,3PA,3P%,FTM,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TO,PTS,DD2,TD3
0,Aerial Powers,DAL,F,183,71.0,21.200991,US,"January 17, 1994",23,Michigan State,2,8,173,30,85,35.3,12,32,37.5,21,26,80.8,6,22,28,12,3,6,12,93,0,0
1,Alana Beard,LA,G/F,185,73.0,21.329438,US,"May 14, 1982",35,Duke,12,30,947,90,177,50.8,5,18,27.8,32,41,78.0,19,82,101,72,63,13,40,217,0,0
2,Alex Bentley,CON,G,170,69.0,23.875433,US,"October 27, 1990",26,Penn State,4,26,617,82,218,37.6,19,64,29.7,35,42,83.3,4,36,40,78,22,3,24,218,0,0
3,Alex Montgomery,SAN,G/F,185,84.0,24.543462,US,"December 11, 1988",28,Georgia Tech,6,31,721,75,195,38.5,21,68,30.9,17,21,81.0,35,134,169,65,20,10,38,188,2,0
4,Alexis Jones,MIN,G,175,78.0,25.469388,US,"August 5, 1994",23,Baylor,R,24,137,16,50,32.0,7,20,35.0,11,12,91.7,3,9,12,12,7,0,14,50,0,0
5,Alexis Peterson,SEA,G,170,63.0,21.799308,US,"June 20, 1995",22,Syracuse,R,14,90,9,34,26.5,2,9,22.2,6,6,100.0,3,13,16,11,5,0,11,26,0,0
6,Alexis Prince,PHO,G,188,81.0,22.917610,US,"February 5, 1994",23,Baylor,R,16,112,9,34,26.5,4,15,26.7,2,2,100.0,1,14,15,5,4,3,3,24,0,0
7,Allie Quigley,CHI,G,178,64.0,20.199470,US,"June 20, 1986",31,DePaul,8,26,847,166,319,52.0,70,150,46.7,40,46,87.0,9,83,92,95,20,13,59,442,0,0
8,Allisha Gray,DAL,G,185,76.0,22.205990,US,"October 20, 1992",24,South Carolina,2,30,834,131,346,37.9,29,103,28.2,104,129,80.6,52,75,127,40,47,19,37,395,0,0
9,Allison Hightower,WAS,G,178,77.0,24.302487,US,"June 4, 1988",29,LSU,5,7,103,14,38,36.8,2,11,18.2,6,6,100.0,3,7,10,10,5,0,2,36,0,0
10,Alysha Clark,SEA,F,180,76.0,23.456790,US,"July 7, 1987",30,Middle Tennessee,6,30,843,93,183,50.8,20,62,32.3,38,51,74.5,29,97,126,50,22,4,32,244,0,0
11,Alyssa Thomas,CON,F,188,84.0,23.766410,US,"December 4, 1992",24,Maryland,3,28,833,154,303,50.8,0,3,0.0,91,158,57.6,34,158,192,136,48,11,87,399,4,0
12,Amanda Zahui B.,NY,C,196,113.0,29.414827,SE,"August 9, 1993",24,Minnesota,3,25,133,20,53,37.7,2,8,25.0,9,12,75.0,5,18,23,7,4,5,12,51,0,0
13,Amber Harris,CHI,F,196,88.0,22.907122,US,"January 16, 1988",29,Xavier,3,22,146,18,44,40.9,0,10,0.0,5,8,62.5,12,28,40,5,3,9,6,41,0,0
14,Aneika Henry,ATL,F/C,193,87.0,23.356332,JM,"February 13, 1986",31,Florida,6,4,22,4,4,100.0,0,0,0.0,0,0,0.0,0,4,4,1,2,0,3,8,0,0
15,Angel Robinson,PHO,F/C,198,88.0,22.446689,US,"August 30, 1995",21,Arizona State,1,15,237,25,44,56.8,1,1,100.0,7,7,100.0,16,42,58,8,1,11,16,58,0,0
16,Asia Taylor,WAS,F,185,76.0,22.205990,US,"August 22, 1991",26,Louisville,3,20,128,10,31,32.3,0,0,0.0,11,18,61.1,16,21,37,9,5,2,10,31,0,0
17,Bashaara Graves,CHI,F,188,91.0,25.746944,US,"March 17, 1994",23,Tennessee,1,5,59,8,14,57.1,0,0,0.0,3,4,75.0,4,13,17,3,0,1,3,19,0,0
18,Breanna Lewis,DAL,C,196,93.0,24.208663,US,"June 22, 1994",23,Kansas State,R,12,50,2,12,16.7,0,0,0.0,3,4,75.0,2,7,9,2,0,0,7,7,0,0
19,Breanna Stewart,SEA,F/C,193,77.0,20.671696,US,"August 27, 1994",22,Connecticut,2,29,952,201,417,48.2,46,123,37.4,136,171,79.5,43,206,249,78,29,47,68,584,8,0
20,Bria Hartley,NY,G,173,66.0,22.052190,US,"September 30, 1992",24,Connecticut,4,29,598,80,192,41.7,32,93,34.4,25,33,75.8,7,50,57,58,15,5,44,217,0,0
21,Bria Holmes,ATL,G,185,77.0,22.498174,US,"April 19, 1994",23,West Virginia,R,28,655,85,231,36.8,9,50,18.0,56,84,66.7,29,56,85,52,23,7,31,235,0,0
22,Briann January,IND,G,173,65.0,21.718066,US,"November 1, 1987",29,Arizona State,9,25,657,81,205,39.5,18,57,31.6,58,71,81.7,12,25,37,98,23,4,53,238,0,0
23,Brionna Jones,CON,F,191,104.0,28.507990,US,"December 18, 1995",21,Maryland,R,19,112,14,26,53.8,0,0,0.0,16,19,84.2,11,14,25,2,7,1,7,44,0,0
24,Brittany Boyd,NY,G,175,71.0,23.183673,US,"November 6, 1993",23,UC Berkeley,3,2,32,9,15,60.0,0,1,0.0,8,11,72.7,3,5,8,5,3,0,2,26,0,0
25,Brittney Griner,PHO,C,206,93.0,21.915355,US,"October 18, 1990",26,Baylor,5,22,682,167,293,57.0,0,0,0.0,127,154,82.5,43,129,172,39,13,54,52,461,6,0
26,Brittney Sykes,ATL,G,175,66.0,21.551020,US,"July 2, 1994",23,Rutgers,10,30,734,146,362,40.3,29,87,33.3,76,102,74.5,25,94,119,59,18,17,49,397,1,0
27,Camille Little,PHO,F,188,82.0,23.200543,US,"January 18, 1985",32,North Carolina,11,30,759,93,219,42.5,9,52,17.3,33,52,63.5,42,71,113,42,28,13,50,228,0,0
28,Candace Parker,LA,F/C,193,79.0,21.208623,US,"April 19, 1986",31,Tennessee,10,29,889,183,383,47.8,40,114,35.1,88,115,76.5,37,205,242,127,43,53,80,494,10,1
29,Candice Dupree,IND,F,188,81.0,22.917610,US,"February 25, 1984",33,Temple,12,29,911,189,370,51.1,0,2,0.0,57,65,87.7,31,124,155,47,28,12,42,435,2,0
30,Cappie Pondexter,CHI,G,175,73.0,23.836735,US,"July 1, 1983",34,Rutgers,11,24,676,94,258,36.4,8,32,25.0,54,67,80.6,10,59,69,104,17,5,56,250,2,0
31,Carolyn Swords,SEA,C,198,95.0,24.232221,US,"July 19, 1989",28,Boston College,6,26,218,19,39,48.7,0,0,0.0,16,20,80.0,10,29,39,9,5,4,22,54,0,0
32,Cayla George,PHO,C,193,87.0,23.356332,AU,"April 20, 1987",30,Georgia,1,28,365,40,105,38.1,13,45,28.9,7,12,58.3,10,71,81,15,9,11,13,100,1,0
33,Chelsea Gray,LA,G,180,77.0,23.765432,US,"August 10, 1992",25,Duke,3,30,996,165,326,50.6,48,100,48.0,78,94,83.0,19,80,99,132,29,7,61,456,1,0
34,Cheyenne Parker,CHI,F,193,86.0,23.087868,US,"August 22, 1992",25,Middle Tennessee,2,23,286,32,69,46.4,0,3,0.0,23,36,63.9,31,47,78,13,8,15,21,87,0,0
35,Clarissa dos Santos,SAN,C,185,89.0,26.004383,BR,"October 3, 1988",28,Brazil,4,7,52,8,14,57.1,1,1,100.0,0,0,0.0,3,7,10,7,1,1,5,17,0,0
36,Courtney Paris,DAL,C,193,113.0,30.336385,US,"September 21, 1987",29,Oklahoma,7,16,217,32,57,56.1,0,0,0.0,6,12,50.0,28,34,62,5,6,8,18,70,0,0
37,Courtney Vandersloot,CHI,G,173,66.0,22.052190,US,"August 2, 1989",28,Gonzaga,6,22,673,104,199,52.3,23,60,38.3,24,29,82.8,13,75,88,175,22,5,64,255,10,0
38,Courtney Williams,CON,G,173,62.0,20.715694,US,"November 5, 1994",22,South Florida,1,29,755,168,338,49.7,8,30,26.7,31,36,86.1,38,84,122,60,15,6,39,375,1,0
39,Crystal Langhorne,SEA,F/C,188,84.0,23.766410,US,"October 27, 1986",30,Maryland,10,30,848,160,240,66.7,1,2,50.0,49,68,72.1,35,140,175,46,16,11,50,370,2,0
40,Damiris Dantas,ATL,C,191,89.0,24.396261,BR,"November 17, 1992",24,Brazil,4,30,569,98,243,40.3,25,91,27.5,33,43,76.7,29,84,113,19,17,18,26,254,0,0
41,Danielle Adams,CON,F/C,185,108.0,31.555880,US,"February 19, 1989",28,Texas A&M,5,18,81,16,43,37.2,12,30,40.0,5,5,100.0,6,4,10,4,4,4,7,49,0,0
42,Danielle Robinson,PHO,G,175,57.0,18.612245,US,"October 5, 1989",27,Oklahoma,7,28,680,79,178,44.4,0,5,0.0,51,61,83.6,13,73,86,106,33,4,58,209,0,0
43,Dearica Hamby,SAN,F,191,86.0,23.573915,US,"June 11, 1993",24,Wake Forest,2,31,650,96,207,46.4,3,8,37.5,58,95,61.1,48,91,139,32,29,8,43,253,1,0
44,Devereaux Peters,IND,F,188,79.0,22.351743,US,"August 10, 1989",28,Notre Dame,6,28,796,154,380,40.5,88,225,39.1,118,130,90.8,8,69,77,76,16,9,56,514,0,0
45,Diana Taurasi,PHO,G,183,74.0,22.096808,US,"November 6, 1982",34,Connecticut,13,20,591,121,255,47.5,22,66,33.3,112,118,94.9,31,98,129,32,20,31,28,376,3,0
46,Elena Delle Donne,WAS,G/F,196,85.0,22.126197,US,"May 9, 1989",28,Delaware,5,30,939,133,272,48.9,0,1,0.0,51,78,65.4,99,116,215,43,32,64,36,317,4,0
47,Elizabeth Williams,ATL,F/C,191,87.0,23.848030,US,"June 23, 1993",24,Duke,3,30,377,48,96,50.0,0,1,0.0,32,55,58.2,35,61,96,5,5,4,21,128,0,0
48,Emma Cannon,PHO,F,188,86.0,24.332277,US,"January 6, 1989",28,Central Florida,R,18,508,105,220,47.7,11,33,33.3,31,34,91.2,33,72,105,52,21,27,30,252,1,0
49,Emma Meesseman,WAS,C,193,83.0,22.282477,BE,"May 13, 1993",24,Belgium,5,23,617,89,233,38.2,25,79,31.6,56,65,86.2,23,58,81,70,34,5,30,259,0,0
50,Epiphanny Prince,NY,G,175,81.0,26.448980,US,"November 1, 1988",28,Rutgers,8,26,282,36,86,41.9,1,3,33.3,15,22,68.2,17,44,61,5,4,8,17,88,0,0
51,Erica Wheeler,IND,G,170,65.0,22.491349,US,"February 5, 1991",26,Rutgers,3,30,767,130,321,40.5,42,129,32.6,34,40,85.0,11,57,68,117,38,1,68,336,0,0
52,Érika de Souza,SAN,C,196,86.0,22.386506,BR,"September 3, 1982",34,Brazil,13,30,579,65,112,58.0,0,0,0.0,29,32,90.6,58,74,132,35,18,7,37,159,0,0
53,Erlana Larkins,IND,F,185,93.0,27.173119,US,"February 4, 1986",31,North Carolina,9,20,386,36,92,39.1,9,35,25.7,21,24,87.5,9,26,35,24,11,8,13,102,0,0
54,Essence Carson,LA,G/F,183,74.0,22.096808,US,"July 28, 1986",31,Rutgers,10,15,61,4,16,25.0,0,0,0.0,5,6,83.3,7,2,9,0,1,3,5,13,0,0
55,Evelyn Akhator,DAL,F,191,82.0,22.477454,NG,"March 2, 1995",22,Kentucky,R,30,926,165,365,45.2,20,60,33.3,92,117,78.6,73,199,272,50,37,13,67,442,13,0
56,Glory Johnson,DAL,F,191,77.0,21.106878,US,"July 27, 1990",27,Tennessee,4,4,42,3,9,33.3,3,6,50.0,0,0,0.0,0,3,3,1,0,0,4,9,0,0
57,Imani Boyette,ATL,C,201,88.0,21.781639,US,"November 10, 1992",24,Texas,1,29,410,56,119,47.1,1,3,33.3,14,20,70.0,43,75,118,14,9,23,22,127,1,0
58,Isabelle Harrison,SAN,C,191,83.0,22.751569,US,"September 27, 1993",23,Kentucky,3,31,832,154,300,51.3,1,2,50.0,55,85,64.7,66,134,200,46,26,24,63,364,5,0
59,Ivory Latta,WAS,G,168,63.0,22.321429,US,"September 25, 1984",32,North Carolina,12,29,499,79,218,36.2,40,114,35.1,47,55,85.5,7,20,27,49,12,1,22,245,0,0
60,Jantel Lavender,LA,C,193,84.0,22.550941,US,"December 11, 1988",28,Ohio State,7,28,481,89,184,48.4,4,13,30.8,18,22,81.8,31,56,87,28,8,5,35,200,0,0
61,Jasmine Thomas,CON,G,175,66.0,21.551020,US,"September 30, 1989",27,Duke,6,27,762,151,341,44.3,50,116,43.1,39,55,70.9,9,55,64,118,45,4,58,391,1,0
62,Jazmon Gwathmey,IND,G,188,65.0,18.390675,PR,"January 24, 1993",24,James Madison,2,24,371,50,140,35.7,12,49,24.5,30,39,76.9,15,34,49,17,13,19,32,142,0,0
63,Jeanette Pohlen,IND,G,183,78.0,23.291230,US,"February 5, 1989",28,Stanford,6,25,278,20,52,38.5,13,29,44.8,17,20,85.0,3,19,22,13,5,0,15,70,0,0
64,Jennifer Hamson,IND,C,201,95.0,23.514269,US,"January 23, 1992",25,Brigham Young,1,10,50,2,12,16.7,0,3,0.0,8,10,80.0,5,6,11,6,2,2,3,12,0,0
65,Jessica Breland,CHI,F,191,77.0,21.106878,US,"February 23, 1988",29,North Carolina,5,10,78,9,16,56.3,0,0,0.0,4,5,80.0,5,13,18,2,1,9,3,22,0,0
66,Jewell Loyd,SEA,G,178,67.0,21.146320,US,"May 10, 1993",24,Notre Dame,3,29,715,116,245,47.3,8,21,38.1,28,37,75.7,50,139,189,46,18,50,57,268,4,0
67,Jia Perkins,MIN,G,173,75.0,25.059307,US,"February 23, 1982",35,Texas Tech,14,30,932,178,420,42.4,47,123,38.2,114,134,85.1,24,72,96,103,41,11,83,517,0,0
68,Jonquel Jones,CON,F/C,198,86.0,21.936537,BS,"May 1, 1994",23,George Washington,1,29,463,47,124,37.9,11,32,34.4,11,15,73.3,11,46,57,39,30,1,24,116,0,0
69,Jordan Hooper,CHI,F,188,84.0,23.766410,US,"February 20, 1992",25,Nebraska,3,29,833,164,299,54.8,22,49,44.9,117,142,82.4,108,226,334,40,29,46,46,467,17,0
70,Kaela Davis,DAL,G,188,77.0,21.785876,US,"March 15, 1995",22,South Carolina,R,23,208,27,75,36.0,20,55,36.4,3,4,75.0,2,20,22,5,7,1,6,77,0,0
71,Kahleah Copper,CHI,G/F,185,70.0,20.452885,US,"August 28, 1994",22,Rutgers,1,29,475,62,163,38.0,12,32,37.5,49,65,75.4,10,33,43,32,13,3,48,185,0,0
72,Kaleena Mosqueda-Lewis,SEA,F,180,82.0,25.308642,US,"March 11, 1993",24,Connecticut,3,29,369,60,140,42.9,5,23,21.7,36,45,80.0,11,43,54,11,9,2,22,161,0,0
73,Karima Christmas-Kelly,DAL,G/F,183,82.0,24.485652,US,"November 9, 1989",27,Duke,6,14,142,23,43,53.5,9,21,42.9,10,10,100.0,4,10,14,6,1,1,13,65,0,0
74,Kayla Alexander,SAN,C,193,88.0,23.624795,CA,"May 1, 1991",26,Arizona State,4,30,889,91,239,38.1,25,83,30.1,111,129,86.0,45,75,120,65,39,5,50,318,0,0
75,Kayla McBride,SAN,G/F,180,79.0,24.382716,US,"June 25, 1992",25,Notre Dame,3,31,433,78,141,55.3,0,0,0.0,15,16,93.8,40,47,87,17,13,15,30,171,0,0
76,Kayla Pedersen,CON,F,193,86.0,23.087868,US,"April 14, 1989",28,Stanford,5,27,882,128,337,38.0,47,147,32.0,108,118,91.5,12,93,105,59,32,5,54,411,0,0
77,Kayla Thornton,DAL,F,185,86.0,25.127831,US,"October 20, 1992",24,Texas–El Paso,2,21,224,11,30,36.7,0,1,0.0,10,14,71.4,19,26,45,13,6,2,9,32,0,0
78,Keisha Hampton,CHI,F,185,78.0,22.790358,US,"February 22, 1990",27,DePaul,1,30,504,64,157,40.8,14,52,26.9,65,81,80.2,36,59,95,24,20,7,21,207,0,0
79,Kelsey Plum,SAN,G,173,66.0,22.052190,US,"August 24, 1994",23,Washington,R,28,610,73,210,34.8,29,78,37.2,50,58,86.2,11,42,53,91,13,4,72,225,0,0
80,Kia Vaughn,NY,C,193,90.0,24.161722,US,"January 24, 1987",30,Rutgers,9,23,455,62,116,53.4,0,0,0.0,10,19,52.6,39,71,110,16,8,9,21,134,1,0
81,Kiah Stokes,NY,C,191,87.0,23.848030,US,"March 30, 1993",24,Connecticut,3,29,576,50,98,51.0,0,1,0.0,41,52,78.8,63,122,185,21,8,32,33,141,3,0
82,Kristi Toliver,WAS,G,170,59.0,20.415225,US,"January 27, 1987",30,Maryland,9,29,845,119,284,41.9,67,194,34.5,44,49,89.8,9,50,59,91,20,8,48,349,0,0
83,Krystal Thomas,WAS,C,196,88.0,22.907122,US,"October 6, 1989",27,Duke,6,29,737,81,149,54.4,0,0,0.0,37,61,60.7,97,172,269,30,15,31,45,199,2,0
84,Lanay Montgomery,SEA,C,196,96.0,24.989588,US,"September 17, 1993",23,West Virginia,R,7,28,3,7,42.9,0,0,0.0,0,0,0.0,0,5,5,0,1,4,2,6,0,0
85,Layshia Clarendon,ATL,G,175,64.0,20.897959,US,"February 5, 1991",26,UC Berkeley,5,30,900,124,320,38.8,8,53,15.1,73,81,90.1,27,88,115,206,29,1,82,329,3,0
86,Leilani Mitchell,PHO,G,165,58.0,21.303949,US,"June 15, 1985",32,Utah,9,30,623,70,182,38.5,31,92,33.7,62,75,82.7,12,57,69,108,26,9,50,233,0,0
87,Lindsay Allen,NY,G,173,65.0,21.718066,US,"March 20, 1995",22,Notre Dame,R,23,314,21,50,42.0,0,11,0.0,6,9,66.7,8,28,36,47,13,1,18,48,0,0
88,Lindsay Whalen,MIN,G,175,78.0,25.469388,US,"September 5, 1982",34,Minnesota,14,22,520,69,153,45.1,12,34,35.3,27,36,75.0,8,46,54,90,11,2,44,177,0,0
89,Lynetta Kizer,CON,C,193,104.0,27.920213,US,"April 4, 1990",27,Maryland,5,20,238,48,100,48.0,0,1,0.0,23,30,76.7,22,35,57,6,11,7,10,119,0,0
90,Maimouna Diarra,LA,C,198,90.0,22.956841,SN,"January 30, 1991",26,Sengal,R,9,16,1,3,33.3,0,0,0.0,1,2,50.0,3,4,7,1,1,0,3,3,0,0
91,Makayla Epps,CHI,G,178,NaN,NaN,US,"June 6, 1995",22,Kentucky,R,14,52,2,14,14.3,0,5,0.0,2,5,40.0,2,0,2,4,1,0,4,6,0,0
92,Marissa Coleman,IND,G/F,185,73.0,21.329438,US,"April 1, 1987",30,Maryland,9,30,539,50,152,32.9,27,79,34.2,27,33,81.8,7,53,60,25,8,4,34,154,0,0
93,Matee Ajavon,ATL,G,173,73.0,24.391059,US,"July 5, 1986",31,Syracruse,R,27,218,22,69,31.9,0,3,0.0,29,35,82.9,8,26,34,27,10,0,26,73,0,0
94,Maya Moore,MIN,F,183,80.0,23.888441,US,"November 6, 1989",27,Connecticut,7,29,904,170,398,42.7,52,132,39.4,98,114,86.0,50,106,156,99,53,13,56,490,3,0
95,Monique Currie,PHO,G/F,183,80.0,23.888441,US,"February 25, 1983",34,Duke,11,32,717,121,284,42.6,37,93,39.8,85,103,82.5,19,103,122,67,22,11,48,364,0,0
96,Morgan Tuck,CON,F,188,91.0,25.746944,US,"April 30, 1994",23,Connecticut,1,17,294,35,101,34.7,8,28,28.6,13,16,81.3,9,34,43,19,7,0,15,91,1,0
97,Moriah Jefferson,SAN,G,168,55.0,19.486961,US,"August 3, 1994",23,Connecticut,1,21,514,81,155,52.3,9,20,45.0,20,27,74.1,6,31,37,92,33,2,43,191,0,0
98,Natalie Achonwa,IND,C,193,83.0,22.282477,CA,"November 22, 1992",24,Notre Dame,3,30,529,82,151,54.3,0,0,0.0,43,55,78.2,31,70,101,21,11,16,25,207,0,0
99,Natasha Cloud,WAS,G,183,73.0,21.798202,US,"February 22, 1992",25,Saint Joseph's,3,24,448,37,118,31.4,12,51,23.5,20,27,74.1,7,52,59,69,17,3,23,106,0,0
100,Natasha Howard,MIN,F,188,75.0,21.220009,US,"February 9, 1991",26,Florida State,4,29,315,48,104,46.2,3,13,23.1,17,23,73.9,25,38,63,16,11,19,20,116,0,0
101,Nayo Raincock-Ekunwe,NY,F/C,188,79.0,22.351743,CA,"August 29, 1991",25,Simon Fraser,R,27,243,33,63,52.4,0,4,0.0,30,49,61.2,24,22,46,8,2,1,13,96,0,0
102,Nia Coffey,SAN,F,185,77.0,22.498174,US,"May 21, 1995",22,Northwestern,R,25,203,16,59,27.1,0,4,0.0,16,22,72.7,16,30,46,6,5,6,14,48,0,0
103,Nneka Ogwumike,LA,F,188,79.0,22.351743,US,"February 7, 1990",27,Stanford,6,30,948,215,386,55.7,18,49,36.7,129,148,87.2,57,179,236,63,53,14,47,577,9,0
104,Noelle Quinn,SEA,G,183,81.0,24.187046,US,"March 1, 1985",32,UCLA,11,29,459,24,58,41.4,14,35,40.0,17,18,94.4,1,48,49,78,12,5,27,79,0,0
105,Odyssey Sims,LA,G,173,73.0,24.391059,US,"July 13, 1992",25,Baylor,4,27,626,86,198,43.4,11,49,22.4,47,55,85.5,10,34,44,87,38,5,39,230,1,0
106,Plenette Pierson,MIN,F/C,188,88.0,24.898144,US,"August 31, 1981",35,Texas Tech,15,29,402,54,142,38.0,17,51,33.3,15,20,75.0,13,49,62,48,12,4,33,140,0,0
107,Rachel Banham,CON,G,175,76.0,24.816327,US,"July 15, 1993",24,Minnesota,2,26,238,32,87,36.8,16,48,33.3,16,20,80.0,2,27,29,20,4,0,12,96,0,0
108,Ramu Tokashiki,SEA,F,193,80.0,21.477087,JP,"November 6, 1991",25,Japan,1,29,378,42,92,45.7,0,3,0.0,22,27,81.5,19,29,48,16,8,8,25,106,0,0
109,Rebecca Allen,NY,G/F,188,74.0,20.937076,AU,"June 11, 1992",25,Australia,3,28,254,31,86,36.0,14,40,35.0,2,6,33.3,13,51,64,15,9,12,17,78,0,0
110,Rebekkah Brunson,MIN,F,188,84.0,23.766410,US,"November 12, 1981",35,Georgetown,14,26,719,97,218,44.5,22,60,36.7,62,83,74.7,46,135,181,40,31,9,42,278,2,0
111,Renee Montgomery,MIN,G,170,63.0,21.799308,US,"February 12, 1986",31,Connecticut,9,29,614,71,181,39.2,30,89,33.7,44,51,86.3,12,34,46,96,24,1,43,216,0,0
112,Riquna Williams,LA,G,170,75.0,25.951557,US,"May 28, 1990",27,Miami (FL),5,23,408,45,140,32.1,20,74,27.0,38,44,86.4,6,26,32,16,19,3,26,148,0,0
113,Sami Whitcomb,SEA,G,178,66.0,20.830703,US,"July 20, 1988",29,Washington,R,29,354,46,120,38.3,33,94,35.1,14,17,82.4,12,40,52,24,22,0,24,139,0,0
114,Sancho Lyttle,ATL,F,193,79.0,21.208623,ES,"September 20, 1983",33,Houston,13,25,703,71,163,43.6,1,7,14.3,13,19,68.4,42,138,180,41,40,17,34,156,0,0
115,Sandrine Gruda,LA,F/C,193,84.0,22.550941,FR,"June 25, 1987",30,France,5,4,12,1,3,33.3,0,0,0.0,0,0,0.0,0,2,2,0,0,0,2,2,0,0
116,Saniya Chong,DAL,G,173,64.0,21.383942,US,"June 27, 1994",23,Connecticut,R,29,348,27,74,36.5,8,35,22.9,25,29,86.2,9,19,28,33,21,3,23,87,0,0
117,Seimone Augustus,MIN,G/F,183,77.0,22.992624,US,"April 30, 1984",33,LSU,12,27,756,125,251,49.8,18,41,43.9,30,35,85.7,12,70,82,108,17,1,39,298,1,0
118,Sequoia Holmes,SAN,G,185,70.0,20.452885,US,"June 13, 1986",31,UNLV,2,24,280,31,89,34.8,13,46,28.3,6,11,54.5,12,12,24,23,13,5,11,81,0,0
119,Shatori Walker-Kimbrough,WAS,G,180,64.0,19.753086,US,"May 18, 1995",22,Maryland,R,22,260,29,78,37.2,9,26,34.6,29,32,90.6,4,13,17,10,11,1,12,96,0,0
120,Shavonte Zellous,NY,G,178,85.0,26.827421,US,"August 28, 1986",30,Pittsburgh,9,29,865,107,249,43.0,14,41,34.1,118,144,81.9,30,92,122,87,23,8,62,346,1,0
121,Shay Murphy,SAN,G,180,74.0,22.839506,US,"April 15, 1985",32,Southern California,9,23,242,23,62,37.1,12,35,34.3,8,12,66.7,12,26,38,17,10,1,12,66,0,0
122,Shekinna Stricklen,CON,G/F,188,81.0,22.917610,US,"July 30, 1990",27,Tennessee,5,29,795,80,202,39.6,59,149,39.6,26,31,83.9,15,71,86,30,36,2,23,245,0,0
123,Shenise Johnson,IND,G,180,78.0,24.074074,US,"September 12, 1990",26,Miami (FL),6,14,348,55,127,43.3,10,30,33.3,38,40,95.0,13,35,48,35,21,4,18,158,0,0
124,Skylar Diggins-Smith,DAL,G,175,66.0,21.551020,US,"February 8, 1990",27,Notre Dame,4,30,1018,167,394,42.4,43,119,36.1,168,186,90.3,21,86,107,173,38,24,83,545,1,0
125,Stefanie Dolson,CHI,C,196,97.0,25.249896,US,"August 1, 1992",25,Connecticut,3,28,823,162,293,55.3,24,60,40.0,50,58,86.2,35,121,156,65,14,37,65,398,3,0
126,Stephanie Talbot,PHO,G,185,87.0,25.420015,AU,"December 20, 1990",26,Australia,R,30,555,47,114,41.2,15,38,39.5,29,44,65.9,28,58,86,50,22,8,28,138,0,0
127,Sue Bird,SEA,G,175,68.0,22.204082,US,"October 16, 1980",36,Connecticut,15,27,806,103,244,42.2,50,134,37.3,17,24,70.8,7,46,53,177,31,3,57,273,1,0
128,Sugar Rodgers,NY,G,175,75.0,24.489796,US,"August 12, 1989",28,Georgetown,6,28,745,108,310,34.8,59,163,36.2,42,52,80.8,21,85,106,68,28,17,43,317,0,0
129,Sydney Colson,SAN,G,173,64.0,21.383942,US,"June 8, 1989",28,Texas A&M,3,25,296,25,78,32.1,2,10,20.0,20,30,66.7,3,11,14,51,13,2,25,72,0,0
130,Sydney Wiese,LA,G,183,68.0,20.305175,US,"July 13, 1992",25,Oregon State,R,25,189,19,50,38.0,13,32,40.6,4,8,50.0,3,18,21,6,4,3,2,55,0,0
131,Sylvia Fowles,MIN,C,198,96.0,24.487297,US,"June 10, 1985",32,LSU,10,29,895,222,336,66.1,0,0,0.0,128,162,79.0,113,184,297,39,39,61,71,572,16,0
132,Tamera Young,ATL,G/F,188,77.0,21.785876,US,"October 30, 1986",30,Tennessee,9,31,820,105,297,35.4,23,70,32.9,44,65,67.7,23,87,110,66,36,14,61,277,0,0
133,Tayler Hill,WAS,G,175,66.0,21.551020,US,"October 23, 1990",26,Ohio State,5,18,462,69,191,36.1,27,89,30.3,75,80,93.8,5,29,34,47,16,1,26,240,0,0
134,Temi Fagbenle,MIN,C,193,89.0,23.893259,UK,"August 9, 1992",25,Southern California,R,17,74,6,14,42.9,0,0,0.0,5,6,83.3,3,13,16,1,3,3,8,17,0,0

## 1.2 Frequency Distribution Tables

A frequency distribution table has two columns. One column records the unique values of a variable, and the other the frequency of each unique value.

<img width="400" src="https://drive.google.com/uc?export=view&id=1eZ42ytzaA8E1VUaV_fUti5-kzOEL4Jc5">

To generate a frequency distribution table using Python, we can use the [Series.value_counts()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html?highlight=value_counts#pandas.Series.value_counts) method. Let's try it on the **Pos** column, which describes the position on the court of each individual.

```python
>> wnba['Pos'].value_counts()
G      60
F      33
C      25
G/F    13
F/C    12
Name: Pos, dtype: int64
```

**Exercise**

<img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ">


Using the **Series.value_counts()** method, generate frequency distribution tables for the following columns:

- **Pos.** Assign the frequency distribution table to a variable named **freq_distro_pos**.
- **Height.** Assign the frequency distribution table to a variable named **freq_distro_height**.

Using the variable inspector, try to analyze each table and identify how values are distributed and compare to each other.

In [2]:
# put your code here
freq_distro_pos = wnba["Pos"].value_counts()
freq_distro_height = wnba["Height"].value_counts()

print(freq_distro_height)
freq_distro_pos

188    20
193    18
175    16
185    15
191    11
183    11
173    11
196     9
178     8
180     7
170     6
198     5
201     2
168     2
206     1
165     1
Name: Height, dtype: int64

G      60
F      33
C      25
G/F    13
F/C    12
Name: Pos, dtype: int64

## 1.3 Sorting Frequency Distribution Tables

As you might have noticed, pandas sorts the tables by default in the descending order of the frequencies. Let's consider again the frequency distribution table for the Pos variable, which is measured on a nominal scale:

```python
>> wnba['Pos'].value_counts()
G      60
F      33
C      25
G/F    13
F/C    12
Name: Pos, dtype: int64
```

This default is harmless for variables measured on a nominal scale because the unique values, although different, have no direction (we can't say, for instance, that centers are greater or lower than guards). The default actually helps because we can immediately see which values have the greatest or lowest frequencies, we can make comparisons easily, etc.


<img width="600" src="https://drive.google.com/uc?export=view&id=1rF3KN5tNdnTS5Jo8veeBk0Q6ANVSH19x">


For variables measured on **ordinal**, **interval**, or **ratio scales**, this default makes the analysis of the tables more difficult because the unique values have direction (some uniques values are greater or lower than others). Let's consider the table for the **Height** variable, which is measured on a **ratio scale**:

```python
>> wnba['Height'].value_counts()
188    20
193    18
175    16
185    15
191    11
183    11
173    11
196     9
178     8
180     7
170     6
198     5
201     2
168     2
206     1
165     1
Name: Height, dtype: int64
 ```
 
 Because the **Height** variable has direction, we might be interested to find:

- How many players are under 170 cm?
- How many players are very tall (over 185)?
- Are there any players below 160 cm?

It's time-consuming to answer these questions using the table above. The solution is to sort the table ourselves.

**wnba['Height'].value_counts()** returns a **Series** object with the measures of height as indices. This allows us to sort the table by index using the [Series.sort_index()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.sort_index.html) method:

```python
>> wnba['Height'].value_counts().sort_index()
165     1
168     2
170     6
173    11
175    16
178     8
180     7
183    11
185    15
188    20
191    11
193    18
196     9
198     5
201     2
206     1
Name: Height, dtype: int64
```

We can also sort the table by index in a descending order using **wnba['Height'].value_counts().sort_index(ascending = False)**



**Exercise**

<img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ">


- Generate a frequency distribution table for the **Age** variable, which is measured on a **ratio scale**, and sort the table by unique values.
  - Sort the table by unique values in an ascending order, and assign the result to a variable named **age_ascending.**
  - Sort the table by unique values in a descending order, and assign the result to a variable named **age_descending.**

- Analyze one of the frequency distribution tables and brainstorm questions that might be interesting to answer here. These include:
  - How many players are under 20?
  - How many players are 30 or over?

In [3]:
# put your code here
age_ascending = wnba["Age"].value_counts().sort_index()
age_descending = wnba["Age"].value_counts().sort_index(ascending=False)

print(age_ascending)

# Players under 20: none
# Players 30 or over: 38 players

21     2
22    10
23    15
24    16
25    15
26    12
27    13
28    14
29     8
30     9
31     8
32     8
33     3
34     5
35     4
36     1
Name: Age, dtype: int64

## 1.4 Sorting Tables for Ordinal Variables

The sorting techniques learned in the previous screen can't be used for ordinal scales where the measurement is done using words. We don't have a variable measured on an ordinal scale in our data set, but let's use the **PTS** variable and the conventions below to create one and see why the techniques we learned don't work:


<img width="300" src="https://drive.google.com/uc?export=view&id=11c0OU4fvss88CyRX7OBAVetRtgpojL2j">

We name the new column **PTS_ordinal_scale**. Below is a short extract from our data set containing the new column:

```python
>> wnba[['Name', 'PTS', 'PTS_ordinal_scale']].head()
```

<img width="300" src="https://drive.google.com/uc?export=view&id=1TsbZSmvbqIuXkmfXqk_fuknoWSSpFTiL">


Let's examine the frequency distribution table for the **PTS_ordinal_scale** variable:

```python
>> wnba['PTS_ordinal_scale'].value_counts()
a lot of points    79
few points         27
many points        25
very few points    12
dtype: int64
```


We want to sort the labels in an **ascending** or **descending order**, but using **Series.sort_index()** doesn't work because the method can't infer quantities from words like "few points". **Series.sort_index()** can only order the index alphabetically in an ascending or descending order:

```python
>> wnba['PTS_ordinal_scale'].value_counts().sort_index()
a lot of points    79
few points         27
many points        25
very few points    12
dtype: int64
```

The solution is to do selection by index label. The output of **wnba['PTS_ordinal_scale'].value_counts()** is a Series object with the labels as indices. This means we can select by indices to reorder in any way we like:

```python
>> wnba['PTS_ordinal_scale'].value_counts()[['very few points', 'few points', 'many points', 'a lot of points']]
very few points    12
few points         27
many points        25
a lot of points    79
dtype: int64
```

This approach can be time-consuming because it involves more typing than it's ideal. We can use **iloc[]** instead to reorder by position:

```python
>> wnba['PTS_ordinal_scale'].value_counts().iloc[[3, 1, 2, 0]]
very few points    12
few points         27
many points        25
a lot of points    79
dtype: int64
```


**Exercise**

<img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ">

We've added more granularity to the ordinal scale above:

<img width="400" src="https://drive.google.com/uc?export=view&id=1jYoNYmiO4z0S11WD1Yyj98EnYpZ6ky7S">


Generate a frequency distribution table for the transformed **PTS_ordinal_scale** column.

- Order the table by unique values in a descending order (not alphabetically).
- Assign the result to a variable named **pts_ordinal_desc.**

In [4]:
def make_pts_ordinal(row):
    if row['PTS'] <= 20:
        return 'very few points'
    if (20 < row['PTS'] <=  80):
        return 'few points'
    if (80 < row['PTS'] <=  150):
        return 'many, but below average'
    if (150 < row['PTS'] <= 300):
        return 'average number of points'
    if (300 < row['PTS'] <=  450):
        return 'more than average'
    else:
        return 'much more than average'
    
wnba['PTS_ordinal_scale'] = wnba.apply(make_pts_ordinal, axis = 1)

# put your code here
pts_ordinal_desc = wnba['PTS_ordinal_scale'].value_counts().iloc[[4, 3, 0, 2, 1, 5]]
pts_ordinal_desc

much more than average      13
more than average           21
average number of points    45
many, but below average     25
few points                  27
very few points             12
Name: PTS_ordinal_scale, dtype: int64

## 1.5 Proportions and Percentages

When we analyze distributions, we're often interested in answering questions about **proportions** and **percentages**. For instance, we may want to answer the following questions about the distribution of the **POS** (player position) variable:

- What proportion of players are guards?
- What percentage of players are centers?
- What percentage of players have mixed positions?

It's very difficult to answer these questions precisely just by looking at the frequencies:

```python
>> wnba['Pos'].value_counts()
G      60
F      33
C      25
G/F    13
F/C    12
Name: Pos, dtype: int64
```

We can see that almost half of the players are guards, but we need more granularity to answer the first question above. For that, we can transform frequencies to proportions.

The proportion of each player position quantifies how many players play in a certain position **relative** to the total number of players. There are 60 guards and 143 players overall (including guards) so the proportion of guards is $\frac{60}{143}$ .

In practical data analysis, it's much more common to express the fraction as a decimal between 0 and 1. So we'd say that $0.42$  (the result of $\frac{60}{143}$ ) of the players are guards.

<img width="400" src="https://drive.google.com/uc?export=view&id=1gXcSf6vRp7hBb_SXeZYlB-_PPeZtyFyH">

In pandas, we can compute all the proportions at once by dividing each frequency to the total number of players:

```python
>> wnba['Pos'].value_counts() / len(wnba)
G      0.419580
F      0.230769
C      0.174825
G/F    0.090909
F/C    0.083916
Name: Pos, dtype: float64
```

It's slightly faster though to use **Series.value_counts()** with the **normalize** parameter set to **True**:

```python
>> wnba['Pos'].value_counts(normalize = True)
G      0.419580
F      0.230769
C      0.174825
G/F    0.090909
F/C    0.083916
Name: Pos, dtype: float64
```

To find percentages, we just have to multiply the proportions by 100:

```python
>> wnba['Pos'].value_counts(normalize = True) * 100
G      41.958042
F      23.076923
C      17.482517
G/F     9.090909
F/C     8.391608
Name: Pos, dtype: float64
```

<img width="400" src="https://drive.google.com/uc?export=view&id=1gJzhcwdMVcx2y4DHKHw2LsT_WvyBCz55">


Because proportions and percentages are **relative** to the total number of instances in some set of data, they are called **relative frequencies**. In contrast, the frequencies we've been working with so far are called **absolute frequencies** because they are absolute counts and don't relate to the total number of instances.

**Exercise**

<img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ">


- Answer the following questions about the Age variable:
  - What proportion of players are 25 years old? Assign your answer to a variable named **proportion_25.**
  - What percentage of players are 30 years old? Assign your answer to a variable named **percentage_30.**
  - What percentage of players are 30 years or older? Assign your answer to a variable named **percentage_over_30**.
  - What percentage of players are 23 years or younger? Assign your answer to a variable named **percentage_below_23.**

In [38]:
# put your code here
proportion_25 = wnba['Age'].value_counts(normalize = True).iloc[1]
print("Proportion of players with 25: {}".format(proportion_25))

percentage_30 = wnba['Age'].value_counts(normalize = True).iloc[7] * 100
print("Percentage of players with 30: {}".format(percentage_30))

percentage_over_30 = wnba['Age'].value_counts(normalize = True).sort_index().iloc[9:].sum() * 100
print("Percentage of players with 30 or over: {}".format(percentage_over_30))

percentage_below_23 = wnba['Age'].value_counts(normalize = True).sort_index().iloc[[0, 1, 2]].sum() * 100
print("Percentage of players with 23 or younger: {}".format(percentage_below_23))

Proportion of players with 25: 0.1048951048951049
Percentage of players with 30: 6.293706293706294
Percentage of players with 30 or over: 26.573426573426573
Percentage of players with 23 or younger: 18.88111888111888

## 1.6 Percentiles and Percentile Ranks

In the previous exercise, we found that the percentage of players aged 23 years or younger is 19% (rounded to the nearest integer). This percentage is also called a **percentile rank**.

A percentile rank of a value $x$  in a frequency distribution is given by the percentage of values that are equal or less than $x$. In our last exercise, $x=23$, and the fact that 23 has a percentile rank of 19% means that 19% of the values are equal to or less than 23.

In this context, the value of 23 is called the **19th percentile**. If a value $x$  is the 19th percentile, it means that 19% of all the values in the distribution are equal to or less than $x$ .


<img width="600" src="https://drive.google.com/uc?export=view&id=17b-Z_fRcvHgwPl3NJP5G-B7Pxy-EZ5c1">


When we're trying to answer questions similar to **"What percentage of players are 23 years or younger?"**, we're trying to find **percentile ranks.** In our previous exercise, our answer to this question was 18.881%. We can arrive at the same answer a bit faster using the [percentileofscore(a, score, kind='weak')](https://docs.scipy.org/doc/scipy-0.10.0/reference/generated/scipy.stats.percentileofscore.html#scipy-stats-percentileofscore) function from **scipy.stats**:

```python
>> from scipy.stats import percentileofscore
>> percentileofscore(a = wnba['Age'], score = 23, kind = 'weak')
18.88111888111888
```

We need to use **kind = 'weak'** to indicate that we want to find the percentage of values thar are equal to or less than the value we specify in the score parameter.

Another question we had was what percentage of players are 30 years or older. We can answer this question too using percentile ranks. First we need to find the percentage of values equal to or less than 29 years (the percentile rank of 29). The rest of the values must be 30 years or more.

<img width="600" src="https://drive.google.com/uc?export=view&id=1tLUg6nvpy5nOhXCWVEJgpyvD7ldhjCVw">


In our exercise the answer we found was 26.573%. This is what we get using the technique we've just learned:

```python
>> 100 - percentileofscore(wnba['Age'], 29, kind = 'weak')
26.573426573426573
```

In the next sections, we'll learn how to find quickly any percentile using pandas. For now, let's practice percentile ranks more.



**Exercise**

<img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ">

- Import **percentileofscore()** from scipy.stats, and then use it to answer the following questions:
  - What percentage of players played half the number of games or less in the 2016-2017 season (there are 34 games in the WNBA’s regular season)? Use the **Games Played** column to find the data you need, and assign your answer to a variable named **percentile_rank_half_less**.
  - What percentage of players played more than half the number of games of the season 2016-2017? Assign your result to **percentage_half_more.**

In [45]:
from scipy.stats import percentileofscore

percentile_rank_half_less = percentileofscore(wnba["Games Played"], 17, kind = 'weak')
percentage_half_more = 100 - percentile_rank_half_less

print("Played half number of games: {}".format(percentile_rank_half_less))
print("Played more than half number of games: {}".format(percentage_half_more))

Played half number of games: 16.083916083916083
Played more than half number of games: 83.91608391608392

## 1.7 Finding Percentiles with pandas

To find percentiles, we can use the **Series.describe()** method, which returns by default the **25th**, the **50th**, and the **75th** percentiles:

```python
>> wnba['Age'].describe()
count    143.000000
mean      27.076923
std        3.679170
min       21.000000
25%       24.000000
50%       27.000000
75%       30.000000
max       36.000000
Name: Age, dtype: float64
```

We are not interested here in the first three rows of the output (count, mean, and standard deviation). We can use **iloc[]** to isolate just the output we want:

```python
>>wnba['Age'].describe().iloc[3:]
min    21.0
25%    24.0
50%    27.0
75%    30.0
max    36.0
Name: Age, dtype: float64
```

The **25th**, **50th**, and **75th** percentiles pandas returns by default are the scores that divide the distribution into four equal parts.

<img width="500" src="https://drive.google.com/uc?export=view&id=1UI-X7sTvPKAa4xkygiBM8cxkxjpeCBlL">


The three percentiles that divide the distribution in four equal parts are also known as **quartiles** (from the Latin [quartus](http://www.latin-dictionary.net/definition/32600/quattuor-quartus) which means four). There are three quartiles in the distribution of the **Age** variable:

- The first quartile (also called lower quartile) is 24 (note that 24 is also the 25th percentile).
- The second quartile (also called the middle quartile) is 27 (note that 27 is also the 50th percentile).
- And the third quartile (also called the upper quartile) is 30 (note that 30 is also the 75th percentile).

We may be interested to find the percentiles for percentages other than 25%, 50%, or 75%. For that, we can use the **percentiles** parameter of **Series.describe()**. This parameter requires us to pass the **percentages** we want as proportions between 0 and 1.


```python
>> wnba['Age'].describe(percentiles = [.1, .15, .33, .5, .592, .85, .9]).iloc[3:]
min      21.0
10%      23.0
15%      23.0
33%      25.0
50%      27.0
59.2%    28.0
85%      31.0
90%      32.0
max      36.0
Name: Age, dtype: float64
```

Percentiles don't have a single [standard definition](https://en.wikipedia.org/wiki/Percentile#Definitions), so don't be surprised if you get very similar (but not identical) values if you use different functions (especially if the functions come from different libraries).


**Exercise**

<img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ">

- Use the **Age** variable along with **Series.describe()** to answer the following questions:
  - What's the upper quartile of the **Age** variable? Assign your answer to a variable named **age_upper_quartile.**
  - What's the middle quartile of the **Age** variable? Assign your answer to a variable named **age_middle_quartile.**
  - What's the **95th percentile** of the **Age** variable? Assign your answer to a variable named **age_95th_percentile.**
- Indicate the truth value of the following sentences:
  - A **percentile** is a value of a variable, and it corresponds to a certain **percentile rank** in the distribution of that variable. (If you think this is true, assign **True** (boolean, not string) to a variable named **question_1**, otherwise assign **False**.)
  - A **percentile rank** is a numerical value from the distribution of a variable. (Assign **True** or **False** to **question_2**.)
  - The **25th percentile** is the same thing as the **lower quartile**, and the **upper quartile** is the same thing as the **third quartile**. (Assign **True** or **False** to **question_3**)

In [54]:
age_upper_quartile = wnba['Age'].describe().iloc[6]
print("Upper quartile: {}".format(age_upper_quartile))

age_middle_quartile = wnba['Age'].describe().iloc[5]
print("Middle quartile: {}".format(age_middle_quartile))

age_95th_percentile = wnba['Age'].describe(percentiles = [.95]).iloc[5]
print("95th quartile: {}".format(age_95th_percentile))

question_1 = False
question_2 = False
question_3 = True

Upper quartile: 30.0
Middle quartile: 27.0
95th quartile: 34.0

## 2.8 Grouped Frequency Distribution Tables

With frequency tables, we're trying to transform relatively large and incomprehensible amounts of data to a table format we can understand. However, not all frequency tables are straightforward:


```python
>> wnba['Weight'].value_counts().sort_index()
55.0      1
57.0      1
58.0      1
59.0      2
62.0      1
63.0      3
64.0      5
65.0      4
66.0      8
67.0      1
68.0      2
69.0      2
70.0      3
71.0      2
73.0      6
74.0      4
75.0      4
76.0      4
77.0     10
78.0      5
79.0      6
80.0      3
81.0      5
82.0      4
83.0      4
84.0      9
85.0      2
86.0      7
87.0      6
88.0      6
89.0      3
90.0      2
91.0      3
93.0      3
95.0      2
96.0      2
97.0      1
104.0     2
108.0     1
113.0     2
Name: Weight, dtype: int64
```


There's a lot of granularity in the table above, but for this reason it's not easy to find patterns. The table for the **Weight** variable is a relatively happy case - the frequency tables for variables like **PTS**, **BMI**, or **MIN** are even more **daunting**.

If the variable is measured on an **interval** or **ratio scale**, a common solution to this problem is to **group the values in equal intervals**. For the **Weight** variable, the values range from 55 to 113 kg, which amounts to a difference of 58 kg. We can try to segment this 58 kg interval in ten smaller and equal intervals. This will result in ten intervals of 5.8 kg each:

<img width="450" src="https://drive.google.com/uc?export=view&id=12ar9ft_-oVZpZWH_hcjz3awBmhB-ADHg">


Fortunately, pandas can handle this process gracefully. We only need to make use of the **bins** parameter of **Series.value_counts()**. We want ten equal intervals, so we need to specify **bins = 10**:


```python
>> wnba['Weight'].value_counts(bins = 10).sort_index()
(54.941, 60.8]     5
(60.8, 66.6]      21
(66.6, 72.4]      10
(72.4, 78.2]      33
(78.2, 84.0]      31
(84.0, 89.8]      24
(89.8, 95.6]      10
(95.6, 101.4]      3
(101.4, 107.2]     2
(107.2, 113.0]     3
Name: Weight, dtype: int64
 ```
 
(54.941, 60.8], (60.8, 66.6] or (107.2, 113.0] are number intervals. The ( character indicates that the starting point is not included, while the ] indicates that the endpoint is included. (54.941, 60.8] means that 54.941 isn't included in the interval, while 60.8 is. The interval (54.941, 60.8] contains all real numbers greater than 54.941 and less than or equal to 60.8.

We can see above that there are 10 equal intervals, 5.8 each. The first interval, (54.941, 60.8] is confusing, and has to do with [how pandas internals show the output](https://github.com/pandas-dev/pandas/blob/01e99decf14b55409cea0789ffcc615afed45bac/pandas/core/algorithms.py#L497). One way to understand this is to convert 54.941 to 1 decimal point, like all the other values are. Then the first interval becomes (54.9, 60.8]. 54.9 is not included, so you can think that the interval starts at the minimum value of the Weight variable, which is 55.

Because we group values in a table to get a better sense of frequencies in the distribution, the table we generated above is also known as a **grouped frequency distribution table**. Each group (interval) in a grouped frequency distribution table is also known as a **class interval**. (107.2, 113.0], for instance, is a class interval.

Using the grouped frequency distribution table we generated above for the **Weight** variable, we can find patterns easier in the distribution of values:

- Most players weigh somewhere between 70 and 90 kg.
- Very few players weigh over 100 kg.
- Very few players weigh under 60 kg; etc.


**Exercise**

<img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ">

Verify on the cell below and examine the frequency table for the **PTS** (total points) variable trying to find some patterns in the distribution of values. Then, generate a grouped frequency distribution table for the **PTS** variable with the following characteristics:
- The table has 10 class intervals.
- For each class interval, the table shows percentages instead of frequencies.
- The class intervals are sorted in descending order.
- Assign the table to a variable named **grouped_freq_table**, then print it and try again to find some patterns in the distribution of values.

In [59]:
# put your code here
grouped_freq_table = wnba['PTS'].value_counts(bins = 10, normalize = True).sort_index(ascending = False) * 100
grouped_freq_table

(525.8, 584.0]     3.496503
(467.6, 525.8]     2.797203
(409.4, 467.6]     5.594406
(351.2, 409.4]     6.993007
(293.0, 351.2]     5.594406
(234.8, 293.0]    11.888112
(176.6, 234.8]    13.986014
(118.4, 176.6]    11.888112
(60.2, 118.4]     16.783217
(1.417, 60.2]     20.979021
Name: PTS, dtype: float64

## 1.9 Information Loss

When we generate grouped frequency distribution tables, there's an inevitable information loss. Let's consider this table:

```python
>> wnba['PTS'].value_counts(bins = 10)
(1.417, 60.2]     30
(60.2, 118.4]     24
(118.4, 176.6]    17
(176.6, 234.8]    20
(234.8, 293.0]    17
(293.0, 351.2]     8
(351.2, 409.4]    10
(409.4, 467.6]     8
(467.6, 525.8]     4
(525.8, 584.0]     5
Name: PTS, dtype: int64
 ```
 
Looking at the first interval, we can see there are 30 players who scored between 2 and 60 points (2 is the minimum value in our data set, and points in basketball can only be integers). However, because we grouped the values, we lost more granular information like:

- How many players, if any, scored exactly 50 points.
- How many players scored under 10 points.
- How many players scored between 20 and 30 points, etc.

To get back this granular information, we can increase the number of class intervals. However, if we do that, we end up again with a table that's lengthy and very difficult to analyze.

On the other side, if we decrease the number of class intervals, we lose even more information:

```python
wnba['PTS'].value_counts(bins = 5).sort_index()
(1.417, 118.4]    54
(118.4, 234.8]    37
(234.8, 351.2]    25
(351.2, 467.6]    18
(467.6, 584.0]     9
Name: PTS, dtype: int64
```

There are 54 players that scored between 2 and 118 points. We can get this information from the first table above too, but there's some extra information there: among these 54 players, 30 scored between 2 and 60 points, and 24 scored between 61 and 118 points. We lost this information when we decreased the number of class intervals from 10 to 5.

We can conclude there is a trade-off between the information in a table, and how comprehensible the table is.


<img width="450" src="https://drive.google.com/uc?export=view&id=1PtWCiK-ocbotjHqhFxmWL-3j_kAdP9au">



When we increase the number of class intervals, we can get more information, but the table becomes harder to analyze. When we decrease the number of class intervals, we get a boost in comprehensibility, but the amount of information in the table decreases.

As a rule of thumb, 10 is a good number of class intervals to choose because it offers a good balance between information and comprehensibility.

<img width="450" src="https://drive.google.com/uc?export=view&id=1MaCcxrDyJhXd6smlAt-eK41rqRImqKyi">


**Exercise**

<img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ">


Generate a grouped frequency distribution for the **MIN** variable (minutes played during the season), and experiment with the number of class intervals to get a sense for what conclusions you can draw as you vary the number of class intervals. Try to experiment with the following numbers of class intervals:
- 1
- 2
- 3
- 5
- 10
- 15
- 20
- 40

In [62]:
for i in [1, 2, 3, 5, 10, 15, 20, 40]:
  table = wnba['MIN'].value_counts(bins = i, normalize = True).sort_index(ascending = False) * 100
  print("Table with {} value(s): \n{}".format(i, table))
  print("\n\n")

Table with 1 value(s):
(10.993, 1018.0]    100.0
Name: MIN, dtype: float64



Table with 2 value(s):
(515.0, 1018.0]    48.251748
(10.993, 515.0]    51.748252
Name: MIN, dtype: float64



Table with 3 value(s):
(682.667, 1018.0]     31.468531
(347.333, 682.667]    34.965035
(10.993, 347.333]     33.566434
Name: MIN, dtype: float64



Table with 5 value(s):
(816.8, 1018.0]    19.580420
(615.6, 816.8]     20.279720
(414.4, 615.6]     17.482517
(213.2, 414.4]     22.377622
(10.993, 213.2]    20.279720
Name: MIN, dtype: float64



Table with 10 value(s):
(917.4, 1018.0]     6.293706
(816.8, 917.4]     13.286713
(716.2, 816.8]      9.790210
(615.6, 716.2]     10.489510
(515.0, 615.6]      8.391608
(414.4, 515.0]      9.090909
(313.8, 414.4]     10.489510
(213.2, 313.8]     11.888112
(112.6, 213.2]      6.993007
(10.993, 112.6]    13.286713
Name: MIN, dtype: float64



Table with 15 value(s):
(950.933, 1018.0]     2.797203
(883.867, 950.933]    7.692308
(816.8, 883.867]      9.090909
(749.733, 816.8]      5.594406
(682.667, 749.733]    6.293706
(615.6, 682.667]      8.391608
(548.533, 615.6]      6.293706
(481.467, 548.533]    5.594406
(414.4, 481.467]      5.594406
(347.333, 414.4]      9.090909
(280.267, 347.333]    4.195804
(213.2, 280.267]      9.090909
(146.133, 213.2]      2.797203
(79.067, 146.133]     7.692308
(10.993, 79.067]      9.790210
Name: MIN, dtype: float64



Table with 20 value(s):
(967.7, 1018.0]    1.398601
(917.4, 967.7]     4.895105
(867.1, 917.4]     4.895105
(816.8, 867.1]     8.391608
(766.5, 816.8]     2.797203
(716.2, 766.5]     6.993007
(665.9, 716.2]     5.594406
(615.6, 665.9]     4.895105
(565.3, 615.6]     5.594406
(515.0, 565.3]     2.797203
(464.7, 515.0]     4.895105
(414.4, 464.7]     4.195804
(364.1, 414.4]     6.293706
(313.8, 364.1]     4.195804
(263.5, 313.8]     4.195804
(213.2, 263.5]     7.692308
(162.9, 213.2]     2.797203
(112.6, 162.9]     4.195804
(62.3, 112.6]      4.895105
(10.993, 62.3]     8.391608
Name: MIN, dtype: float64



Table with 40 value(s):
(992.85, 1018.0]    1.398601
(967.7, 992.85]     0.000000
(942.55, 967.7]     2.797203
(917.4, 942.55]     2.097902
(892.25, 917.4]     2.797203
(867.1, 892.25]     2.097902
(841.95, 867.1]     4.195804
(816.8, 841.95]     4.195804
(791.65, 816.8]     2.097902
(766.5, 791.65]     0.699301
(741.35, 766.5]     3.496503
(716.2, 741.35]     3.496503
(691.05, 716.2]     2.097902
(665.9, 691.05]     3.496503
(640.75, 665.9]     2.097902
(615.6, 640.75]     2.797203
(590.45, 615.6]     3.496503
(565.3, 590.45]     2.097902
(540.15, 565.3]     0.699301
(515.0, 540.15]     2.097902
(489.85, 515.0]     2.797203
(464.7, 489.85]     2.097902
(439.55, 464.7]     3.496503
(414.4, 439.55]     0.699301
(389.25, 414.4]     2.097902
(364.1, 389.25]     4.195804
(338.95, 364.1]     2.797203
(313.8, 338.95]     1.398601
(288.65, 313.8]     1.398601
(263.5, 288.65]     2.797203
(238.35, 263.5]     2.797203
(213.2, 238.35]     4.895105
(188.05, 213.2]     2.097902
(162.9, 188.05]     0.699301
(137.75, 162.9]     1.398601
(112.6, 137.75]     2.797203
(87.45, 112.6]      2.797203
(62.3, 87.45]       2.097902
(37.15, 62.3]       4.895105
(10.993, 37.15]     3.496503
Name: MIN, dtype: float64

## 1.10 Readability for Grouped Frequency Tables

Pandas helps a lot when we need to explore quickly grouped frequency tables. However, the intervals pandas outputs are confusing at a first sight:

```python
wnba['PTS'].value_counts(bins = 5).sort_index()
(1.417, 118.4]    54
(118.4, 234.8]    37
(234.8, 351.2]    25
(351.2, 467.6]    18
(467.6, 584.0]     9
Name: PTS, dtype: int64
```

Imagine we'd have to publish the table above in a blog post or a scientific paper. The readers will have a hard time understanding the intervals we chose. They'll also be puzzled by the decimal numbers because points in basketball can only be integers.

To fix this, we can define the intervals ourselves. For the table above, we can define six intervals of 100 points each, and then count how many values fit in each interval. We'd like to end with a table like this:


```python
(0,100]      49
(100,200]    28
(200,300]    32
(300,400]    17
(400,500]    10
(500,600]     7
```

Next, we show one way to code the intervals. We start with creating the intervals using the [pd.interval_range()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.interval_range.html?highlight=interval_rang) function:

```python
>> intervals = pd.interval_range(start = 0, end = 600, freq = 100)
>> intervals
IntervalIndex([(0, 100], (100, 200], (200, 300], (300, 400], (400, 500], (500, 600]]
              closed='right',
              dtype='interval[int64]')
```

              
Next, we create a new Series using the intervals as indices, and, for now, 0 as values:

```python
>> gr_freq_table = pd.Series([0,0,0,0,0,0], index = intervals)
>> gr_freq_table
(0, 100]      0
(100, 200]    0
(200, 300]    0
(300, 400]    0
(400, 500]    0
(500, 600]    0
dtype: int64
```

Next, we loop through the values of the **PTS** column, and for each value:

- We loop through the intervals we defined previously, and for each interval:
  - We check whether the current value from the PTS column belongs to that interval.
  - If the value doesn't belong to an interval, we continue the inner loop over the intervals.
  - If the value belongs to an interval:
    - We update the counting for that interval in **gr_freq_table** by adding 1.
    - We exit the inner loop over the intervals with **break** because a value can belong to one interval only, and it makes no sense to continue the loop (without using **break**, we'll get the same output but we'll do many redundant iterations).
    
    
```python
>> for value in wnba['PTS']:
       for interval in intervals:
           if value in interval:
               gr_freq_table.loc[interval] += 1
               break
>> gr_freq_table
(0, 100]      49
(100, 200]    28
(200, 300]    32
(300, 400]    17
(400, 500]    10
(500, 600]     7
dtype: int64
```


Now we do a quick sanity check of our work. There are 143 players in the data set, so the frequencies should add up to 143:

```python
>> gr_freq_table.sum()
143
```

Note that we're not restricted by the minimum and maximum values of a variable when we define intervals. The minimum number of points is 2, and the maximum is 584, but our intervals range from 1 to 600.


**Exercise**

<img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ">


- Using the techniques above, generate a grouped frequency table for the **PTS** variable. The table should have the following characteristics:
  - There are 10 class intervals.
  - The first class interval starts at 0 (not included).
  - The last class interval ends at 600 (included).
  - Each interval has a range of 60 points.
- Assign the table to a variable named **gr_freq_table_10**.

In [65]:
# put your code here
gr_freq_table_10 = pd.Series([0,0,0,0,0,0,0,0,0,0], index = intervals)
intervals = pd.interval_range(start = 0, end = 600, freq = 60)

for value in wnba['PTS']:
  for interval in intervals:
    if value in interval:
      gr_freq_table_10.loc[interval] += 1
      break

gr_freq_table_10

(0, 60]       30
(60, 120]     25
(120, 180]    17
(180, 240]    22
(240, 300]    15
(300, 360]     7
(360, 420]    11
(420, 480]     7
(480, 540]     4
(540, 600]     5
dtype: int64

## 1.11 Frequency Tables and Continuous Variables

Remember from the previous mission that a height of 175 cm is just an interval bounded by the real limits of 174.5 cm (lower real limit) and 175.5 (upper real limit). When we build frequency tables for continuous variables, we need to take into account that the values are intervals.

The height of 175 cm has a frequency of 16 in the distribution of the **Height** variable:

```python
>> wnba['Height'].value_counts()[175]
16
```

This doesn't mean that there are 16 players that are all exactly 175 cm tall. It rather means that there are 16 players with a height that's somewhere between 174.5 cm and 175.5 cm.

A similar reasoning applies when we read grouped frequency tables. If we had an interval of (180, 190] for a continuous variable, 180 and 190 are not the real limits. Instead, the real limits are given by the interval (179.5, 190.5], with 179.5 being the lower real limit of 180, and 190.5 the upper real limit of 190.

Continuous variables affect as well the way we read percentiles. For instance, the 50th percentile (middle quartile) in the distribution of the **Height** variable is 185 cm:


```python
>> wnba['Height'].describe().iloc[3:]
min    165.0
25%    176.5
50%    185.0
75%    191.0
max    206.0
Name: Height, dtype: float64
```

This means that 50% of the values are less or equal to 185.5 cm (the upper limit of 185 cm), not to 185 cm.

## 1.12 Next Steps

In this mission, we learned how to organize data in frequency and grouped frequency tables. Frequency tables allow us to transform large and incomprehensible amounts of data to a format we can understand.



<img width="600" src="https://drive.google.com/uc?export=view&id=1Zp0BuFcG3T0rk4MSaPfw8gpGPdlrQ68I">

Next in the course, we'll learn how to visualize frequency tables using bar plots and histograms.